---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-restic-zhulik-wtf-v1-repository
  failurePolicy: Fail
  name: vrepository-v1.kb.io
  rules:
  - apiGroups:
    - restic.zhulik.wtf
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
