# This rule is not used by the project restic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to restic.zhulik.wtf resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: restic-operator
    app.kubernetes.io/managed-by: kustomize
  name: key-viewer-role
rules:
- apiGroups:
  - restic.zhulik.wtf
  resources:
  - keys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - restic.zhulik.wtf
  resources:
  - keys/status
  verbs:
  - get
