# This rule is not used by the project restic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the restic.zhulik.wtf.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: restic-operator
    app.kubernetes.io/managed-by: kustomize
  name: repository-editor-role
rules:
- apiGroups:
  - restic.zhulik.wtf
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - restic.zhulik.wtf
  resources:
  - repositories/status
  verbs:
  - get
